version: '3.8'
services:
  db:
    image: postgres:16.2
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommercer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./ecommerce-backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    image: backend-image
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommercer_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      API_SECURITY_TOKEN_SECRET: join123
    networks:
       - ecommerce-network
  frontend:
    build:
      context: ./ecommerce-frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    image: frontend-image
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      API_URL: http://backend:8080
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
volumes:
  postgres_data: